"""Insert §17 Reproduction section before §17 References (which becomes §18).

Idempotent: re-running replaces the inserted cells in place.

Usage:
    python scripts/add_reproduction_section.py
"""

from __future__ import annotations

import io
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except AttributeError:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

import nbformat as nbf

REPO_ROOT = Path(__file__).resolve().parent.parent
NB_PATH = REPO_ROOT / "notebook" / "Capstone_Final_Notebook.ipynb"

REPRODUCTION_CELL = """\
---
## 17. Reproduction

This notebook is the **single source of truth** for the AUROC values, figures, and
tables reported in the manuscript. Reproducing the results end-to-end requires:

### Data
1. Credentialed access to **MIMIC-IV v3.1** via PhysioNet
   (<https://physionet.org/content/mimiciv/3.1/>).
2. The seven training tables (`training_table_v{1..5,6_full,7}.parquet`) built by
   the upstream DuckDB pipeline — see [`data_prep/README.md`](../data_prep/README.md)
   for the construction recipe and version definitions.

### Environment
- Python 3.12.x (developed on 3.12.3 via Anaconda)
- Pinned library versions in [`environment.yml`](../environment.yml) and
  [`requirements.txt`](../requirements.txt)
- Tested on Windows 11 (cp1252 locale); the notebook explicitly forces UTF-8
  output so cross-platform reproduction should be clean.

### Run

```bash
# Optional: set BASE_DIR to the directory containing Dataset/mimic-parquet/
export MEDICARE_READMIT_BASE_DIR=/path/to/your/data/root

# Sanity check (~5–10 min, N_SEEDS=2, progression on V1+V7 only)
python scripts/execute_notebook.py --smoke

# Full publication run (~35–60 min, N_SEEDS=10, full V1→V6 progression)
python scripts/execute_notebook.py
```

### Determinism

- Patient-grouped 80/20 + 10% inner-val split: `random_state=42` (defined in §1.3, used in §8.2).
- Per-model multi-seed averaging: seeds `42, 43, …, 42 + N_SEEDS - 1` in §10.1.
- LogReg, MLP, HistGBM internal early stopping all use `random_state=42`.
- SHAP sample: `random_state=42` in §12.1.

Across machines we observe AUROC variation of ≲0.0010 due to BLAS implementation
differences in LightGBM/XGBoost histogram construction. Each cell prints the
exact realised value alongside the random seed used.

### Repository layout

```
medicare-readmission-publication/
├── README.md            # quickstart + design notes
├── LICENSE              # MIT (code only)
├── CITATION.cff
├── environment.yml      # conda
├── requirements.txt     # pip
├── notebook/
│   └── Capstone_Final_Notebook.ipynb   # ← this file
├── data_prep/
│   ├── README.md
│   └── compare_versions.py
├── scripts/
│   ├── refactor_notebook.py       # converts capstone → publication form
│   ├── execute_notebook.py        # headless runner with --smoke
│   └── add_reproduction_section.py
├── figures/             # regenerated by the notebook
└── results/             # AUROC tables, splits, best params
```

### Mapping notebook → manuscript

| Notebook section | Manuscript section |
|---|---|
| §1 Setup + §1.4 Reproducibility manifest | Methods → Reproducibility |
| §5 Data Source & Cohort | Data & Methods → Cohort |
| §6 EDA | Results → Cohort characteristics |
| §7 Feature Engineering | Methods → Feature engineering |
| §8 Train/val/test protocol | Methods → Evaluation protocol |
| §9 Baselines → Deep Learning progression | Results → Model selection |
| §10 4-GBM ensemble + blending | Results → Final model |
| §11 ROC / calibration / benchmarks | Results → Discrimination & calibration |
| §12 SHAP interpretability | Results → Interpretability |
| §13 Research questions | Discussion |
| §14 Discussion | Discussion |
| §15 Future work | Conclusions |
| §16 Contributions & Conclusions | Conclusions |
"""


def find_cell(nb, needle):
    for i, c in enumerate(nb.cells):
        src = "".join(c.source) if isinstance(c.source, list) else c.source
        if needle in src:
            return i
    raise LookupError(f"cell containing {needle!r} not found")


def main():
    nb = nbf.read(NB_PATH, as_version=4)
    print(f"Loaded {NB_PATH.name}: {len(nb.cells)} cells")

    # The References section currently lives under "## 17. References".
    refs_idx = find_cell(nb, "## 17. References")
    refs_src = "".join(nb.cells[refs_idx].source) if isinstance(nb.cells[refs_idx].source, list) else nb.cells[refs_idx].source

    # Idempotent: if §17 Reproduction is already present (we look for the heading),
    # the References cell will currently say "## 18. References" → skip insertion.
    if "## 18. References" in refs_src:
        # Already inserted; just refresh the Reproduction cell content.
        try:
            rep_idx = find_cell(nb, "## 17. Reproduction")
            nb.cells[rep_idx].source = REPRODUCTION_CELL
            print(f"  [{rep_idx:3d}] §17 Reproduction refreshed (already present)")
        except LookupError:
            pass
    else:
        # First insertion: rename References to §18 and insert Reproduction cell.
        new_refs_src = refs_src.replace("## 17. References", "## 18. References")
        nb.cells[refs_idx].source = new_refs_src

        new_cell = nbf.v4.new_markdown_cell(source=REPRODUCTION_CELL)
        nb.cells.insert(refs_idx, new_cell)
        print(f"  [{refs_idx:3d}] §17 Reproduction inserted (References renumbered to §18)")

    nbf.write(nb, NB_PATH)
    print(f"\nSaved to {NB_PATH}")


if __name__ == "__main__":
    main()
